### ISSUE TITLE
Sen2cor

### ISSUE THREAD

**Issue by dairejpwalsh** [parameterspace-ie/eo4a-service-trials#18]
Is it possible to point Sen2Cor outputs to a specific directory. Having difficulty making Sen2Cor to work correctly on the service.

**Comment by derekocallaghan** [comment]
Are you talking about calling Sen2Cor from your service code? We included it in the Docker image as we'd planned to expose it as a EO4Atlantic service (i.e. a peer of the Sen2Three service - https://docs.eo4a.science/services/atmosphere.html#sen2three). We didn't include it in the end as it consumes an enormous amount of memory, particularly when processing the 10m rasters in an L1C product. As L2A products are available via the Copernicus service, which were themselves created with Sen2Cor, we felt retrieving these instead of processing them with a Sen2Cor service workflow task was sufficient for the pathfinder.

In theory you can call Sen2Cor from service code (like anything else in the container). I'd need to check the user guide but I seem to remember that specifying the output directory isn't possible via the command line (as I originally expected myself), it has to be in some kind of config XML or similar. 

However, given the memory issues with it, I would recommend not using it.

**Comment by derekocallaghan** [comment]
As discussed over email, Sen2Cor won't be used in the pathfinder.
