### ISSUE TITLE
Sen2Three issue

### ISSUE THREAD

**Issue by japoveda** [parameterspace-ie/eo4a-service-trials#8]
Hi,
It seems that the Sen2Three is not returning 3A level of processing as expected. For example, in the following jobs: 
https://portal.eo4a.science/workspace/exec/890
https://portal.eo4a.science/workspace/exec/891

Alex

**Comment by derekocallaghan** [comment]
Hi Alex,

Both of these workflow jobs have the same single L2A product each as input to Sen2Three (S2A_MSIL2A_20171005T113321_N0205_R080_T29UNU_20171005T113316:ad876466-8b90-4fc8-a0d6-f0e008b964c4), as defined in the corresponding 'TM_data_acquisition2' workflow (https://portal.eo4a.science/workflows/754). 

As I mentioned in https://github.com/parameterspace-ie/eo4a-service-trials/issues/6, Sen2Three requires two or more products for a particular region in order to produce the "merged" L3A product. If only one input product is specified, it cannot do any further processing, and the output is the unmodified input product. 

Therefore, both workflow jobs are working as expected given the current workflow parameters.

Derek

**Comment by japoveda** [comment]
Thank you Derek
